require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# IKAIA NOTE: this doesn't necessarily have to match up with swift target versions
# this is just used here to check that dependencies will work with an iOS version
platform :ios, '14.3'

target 'zoe' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'zoeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # IKAIA NOTE: if breaks, change use_flipper! to use_flipper!({ 'Flipper-Folly' => '2.3.0' }) or commont out the next four lines completely
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end

target 'zoe-tvOS' do
  # Pods for zoe-tvOS

  target 'zoe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
