# Generated by Django 3.1.6 on 2022-01-05 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('interested_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField(blank=True, default='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('long', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('capacity', models.IntegerField(blank=True, default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_duration', models.DurationField(blank=True, null=True)),
                ('visibility', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default.png', upload_to='event_pics')),
                ('committed_users', models.ManyToManyField(related_name='committed_events', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('interested_users', models.ManyToManyField(related_name='interested_events', to=settings.AUTH_USER_MODEL)),
                ('themes', models.ManyToManyField(to='events.Theme')),
            ],
        ),
    ]
