# Generated by Django 3.1.6 on 2022-01-13 00:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='visibility',
            new_name='is_public',
        ),
        migrations.AddField(
            model_name='event',
            name='date_occurring',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='committed_users',
            field=models.ManyToManyField(blank=True, related_name='committed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='interested_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='themes',
            field=models.ManyToManyField(blank=True, to='events.Theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='interested_users',
            field=models.ManyToManyField(related_name='interests', to=settings.AUTH_USER_MODEL),
        ),
    ]
